remote_theme: mmistakes/minimal-mistakes
title: Portfolio de Maïwenn LE GALL
show_recent_posts: false
description: Voici un aperçu des principaux projets que j'ai réalisés

plugins:
  - jekyll-include-cache

custom_css:
  - assets/css/custom.css
